kind = "web"
previewPath = "/"
title = "Malzz Nokos"
version = "1.0.0"
id = "artifacts/malzz-nokos"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23206

[services.development]
run = "pnpm --filter @workspace/malzz-nokos run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/malzz-nokos", "run", "build" ]
publicDir = "artifacts/malzz-nokos/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23206"
BASE_PATH = "/"
